my_string = input('\nВведите произвольную строку: ')
print('\nКолличество символов в строке: ', len(my_string))
print('\nСтрока в верхнем регистре: ', my_string.upper())
print('\nСтрока в нижнем регистре: ', my_string.lower())
print('\nСтрока без пробелов: ', my_string.replace(' ', ''))
print('\nПервый символ строки: ', my_string[0])
print('\nПоследний символ строки: ', my_string[-1])