# Generated by Django 5.1.3 on 2025-01-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0002_news_alter_buyer_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='News_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size', models.DecimalField(decimal_places=4, max_digits=20)),
                ('description', models.TextField()),
                ('age_limited', models.BooleanField(default=False)),
                ('buyer', models.ManyToManyField(related_name='games_2', to='task1.buyer')),
            ],
        ),
    ]
